name: VariableEnderChests
version: '${project.version}'
main: me.saif.betterenderchests.VariableEnderChests
author: minion325
api-version: 1.13
folia-supported: true
softdepend: [PlaceholderAPI, ChestSort, ShowItem, InteractiveChat]
